[book]
authors = ["James Munns"]
multilingual = false
src = "src"
title = "The Embedded Rust Book"
language = "en"
version = "0.0.2"

#[output.epub]
#additional-resources = ["assets/f3.jpg","assets/verify.jpeg","assets/crates.png"]


[output.html]
git-repository-url = "https://github.com/rust-embedded/book"
